### ISSUE TITLE
Flutter 3 Update

### ISSUE THREAD

**Issue by TekExplorer** [wasabeef/flutter_use#23]
Hello! Just wanted to suggest updating to flutter 3, as I get these warnings when building, and it would be nice to be rid of them :)

![image](https://user-images.githubusercontent.com/30291302/171074817-29cb2cfb-991c-4997-9b2a-4c84901d071b.png)

**Comment by wasabeef** [comment]
@TekExplorer 
I'm sorry for the late reply, just upgrade to v3.
